SILCD/Controllers/CotaParlamentarController.cs
using SILCD.Models;
using SILCD.Repository.Abstract;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SILCD.Controllers {
    public class CotaParlamentarController : BaseController {
        private ICotaParlamentarRepository repositorio;

        public CotaParlamentarController(ICotaParlamentarRepository _repositorio) {
            if (repositorio == null) {
                repositorio = _repositorio;
            }
        }

        public ActionResult Index() {
            return View();
        }

        [HttpGet]
        [AllowAnonymous]
        public ActionResult JsonResultBuscarCotaParlamentarPorTipo() {
            var CotasParlamentaresPorTipo = repositorio.ListarCotaParlamentarPorTipo();
            if (CotasParlamentaresPorTipo != null) {
                List<PieChartViewModels> data = new List<PieChartViewModels>();
                foreach (CotaParlamentarViewModels cota in CotasParlamentaresPorTipo) {
                    data.Add(new PieChartViewModels() { Name = cota.txtDescricao, valor = cota.vlrDocumento });
                }
                return Json(data, JsonRequestBehavior.AllowGet);
            }
            return null;
        }

        //[AllowAnonymous]
        //[HttpGet]
        //public ActionResult Listar() {
        //    var listaCotasParlamentares = repositorio.Listar();
        //    if (listaCotasParlamentares != null) {
        //        return View(listaCotasParlamentares);
        //    }
        //    return View();
        //}
    }
}

SILCD/Controllers/DeputadosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Xml;
using SILCD.br.gov.camara.www;
using SILCD.Models;
using SILCD.Util;
using System.Data;
using SILCD.Repository.Abstract;
using SILCD.Helper;
using SILCD.Enum;
using SILCD.Resources;
using System.Data.SqlClient;
using System.Configuration;

namespace SILCD.Controllers {
    public class DeputadosController : BaseController {

        private IDeputadosRepository repositorio;
        private List<DeputadoViewModel> deputados = new List<DeputadoViewModel>();

        public DeputadosController(IDeputadosRepository _repositorio) {
            if (repositorio == null) {
                repositorio = _repositorio;
            }
        }

        public ActionResult Index() {
            try {
                var deputados = repositorio.List;
                string txtPesquisa = Request["txtPesquisa"];

                if (!String.IsNullOrEmpty(txtPesquisa)) {
                    try {
                        var _deputados = deputados.Where(d => d.Nome.ToUpper().Contains(txtPesquisa.ToUpper()) ||
                                                              d.Uf.Contains(txtPesquisa) ||
                                                              d.Partido.Contains(txtPesquisa)).ToList();
                        deputados = (List<DeputadoViewModel>)_deputados;
                    } catch (Exception erro) {
                        throw new Exception(erro.Message);
                    }
                }

                //BuscarCotaParlamentar();
                //readXmlCotaParlamentar();

                if (deputados != null) {
                    return View(deputados);
                }

                return View(new List<DeputadoViewModel>());

            } catch (Exception erro) {
                throw new Exception(erro.Message);
            }
        }

        public ActionResult ListarPorNome() {
            try {
                var deputados = repositorio.List;
                string txtPesquisa = Request["txtPesquisa"];

                if (!String.IsNullOrEmpty(txtPesquisa)) {
                    var _deputados = deputados.Where(d => d.Nome.ToUpper().Contains(txtPesquisa.ToUpper()) ||
                                                          d.Uf.Contains(txtPesquisa) ||
                                                          d.Partido.Contains(txtPesquisa)).ToList();
                    deputados = (List<DeputadoViewModel>)_deputados;
                }

                if (deputados != null) {
                    return PartialView("ListarPorNome", deputados);
                }

                return PartialView();

            } catch (Exception erro) {
                throw new Exception(erro.Message);
            }
        }

        public ActionResult Detalhe(int id = 0) {
            try {
                var deputado = repositorio.Buscar(id);
                BuscarDetalhes(deputado);
                PreencherPresencaParlamentar(deputado, null, null); //TODO (está com erro, analisar problema)
                if (deputado == null) {
                    return HttpNotFound();
                }
                return View(deputado);
            } catch {
                throw new Exception(Messages.RecordNotFound);
            }
        }

        public ActionResult CotaParlamentar(int id = 0) {
            try {
                if (id > 0) {
                    var CotasParlamentares = repositorio.ListarCotaParlamentar(id);
                    BuscarCotaParlamentarPorReferenciaTipo(id);
                    BuscarCotaParlamentarPorTipo(id);
                    if (CotasParlamentares == null) {
                        return HttpNotFound();
                    }
                    return View(CotasParlamentares);
                }
                return View();
            } catch {
                throw new Exception(Messages.RecordNotFound);
            }
        }

        private void BuscarCotaParlamentarPorReferenciaTipo(int id = 0) {
            if (id > 0) {
                var CotasParlamentaresPorReferenciaTipo = repositorio.ListarCotaParlamentarPorReferenciaTipo(id);
                if (CotasParlamentaresPorReferenciaTipo != null) {
                    TempData["CotaParlamentarPorReferenciaTipo"] = CotasParlamentaresPorReferenciaTipo;
                }
            }
        }

        private void BuscarCotaParlamentarPorTipo(int id = 0) {
            if (id > 0) {
                var CotasParlamentaresPorTipo = repositorio.ListarCotaParlamentarPorTipo(id);
                if (CotasParlamentaresPorTipo != null) {
                    TempData["CotaParlamentarPorTipo"] = CotasParlamentaresPorTipo;
                }
            }
        }

        [HttpGet]
        [AllowAnonymous]
        public ActionResult JsonResultBuscarCotaParlamentarPorTipo(int id = 0) {
            if (id > 0) {
                var CotasParlamentaresPorTipo = repositorio.ListarCotaParlamentarPorTipo(id);
                if (CotasParlamentaresPorTipo != null) {
                    List<PieChartViewModels> data = new List<PieChartViewModels>();
                    foreach (CotaParlamentarViewModels cota in CotasParlamentaresPorTipo) {
                        data.Add(new PieChartViewModels() { Name = cota.txtDescricao, valor = cota.vlrDocumento });
                    }
                    return Json(data, JsonRequestBehavior.AllowGet);
                }
            }
            return null;
        }

        private DeputadoViewModel BuscarDetalhes(DeputadoViewModel deputado) {
            if (deputado != null && deputado.IdeCadastro > 0) {
                return repositorio.BuscarDetalhes(deputado);
            } else {
                return null;
            }
        }

        private DeputadoViewModel PreencherPresencaParlamentar(DeputadoViewModel deputado, string dataIni, string dataFim) {
            if (deputado == null) {
                throw new Exception("Informe o deputado para obter a lista de presença.");
            }

            if (String.IsNullOrEmpty(dataIni)) {
                //dataIni = String.Format("{0:dd/MM/yyyy}", new DateTime(DateTime.Now.Year, DateTime.Now.Month, 1));
                dataIni = String.Format("{0:dd/MM/yyyy}", new DateTime(DateTime.Now.Year, 1, 1));
            }

            if (String.IsNullOrEmpty(dataFim)) {
                dataFim = String.Format("{0:dd/MM/yyyy}", DateTime.Now);
            }

            return repositorio.PreencherPresencaParlamentar(deputado, dataIni, dataFim);
        }

        private void BuscarDistribuicaoPorUF() {
            var deputados = repositorio.Listar().ToList();
            var query = from d in deputados
                        group d by d.Uf into g
                        select new { Uf = g.Key, UfCount = g.Count() };

            SessionHelper.GravarDistribuicaoPorUF(query);

        }

        private void BuscarDistribuicaoPorPartido() {
            var deputados = repositorio.Listar().ToList();
            var query = from d in deputados
                        group d by d.Partido into g
                        select new { Partido = g.Key, PartidoCount = g.Count() };

            SessionHelper.GravarDistribuicaoPorPartido(query);
        }

        private List<CotaParlamentarViewModels> readXmlCotaParlamentar() {
            List<CotaParlamentarViewModels> listaDeCotas = new List<CotaParlamentarViewModels>();
            try {
                string XmlFileUrl = @"C:\Users\fernando.faria\Desktop\AnoAnterior.xml";
                CotaParlamentarViewModels cotaParlamentar = null;
                using (XmlReader reader = new XmlTextReader(XmlFileUrl)) {
                    while (reader.Read()) {
                        if (reader.NodeType == XmlNodeType.Element) {
                            switch (reader.Name) {
                                case "DESPESA":
                                    if (cotaParlamentar != null) {
                                        listaDeCotas.Add(cotaParlamentar);
                                    }
                                    cotaParlamentar = new CotaParlamentarViewModels();
                                    break;
                                case "txNomeParlamentar":
                                    cotaParlamentar.txNomeParlamentar = reader.ReadContentAsString();
                                    break;
                                //case "nuCarteiraParlamentar":
                                //    cotaParlamentar.nuCarteiraParlamentar = int.Parse(reader.ReadContentAsString());
                                //    break;
                                //case "nuLegislatura":
                                //    cotaParlamentar.nuLegislatura = int.Parse(reader.ReadContentAsString());
                                //    break;
                                case "sgUF":
                                    cotaParlamentar.sgUF = reader.ReadContentAsString();
                                    break;
                                case "sgPartido":
                                    cotaParlamentar.sgPartido = reader.ReadContentAsString();
                                    break;
                                //case "codLegislatura":
                                //    cotaParlamentar.codLegislatura = int.Parse(reader.ReadContentAsString());
                                //    break;
                                //case "numSubCota":
                                //    cotaParlamentar.numSubCota = int.Parse(reader.ReadContentAsString());
                                //    break;
                                case "txtDescricao":
                                    cotaParlamentar.txtDescricao = reader.ReadContentAsString();
                                    break;
                                //case "numEspecificacaoSubCota":

SILCD/Controllers/OrgaosController.cs
using SILCD.Enum;
using SILCD.Repository.Abstract;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SILCD.comissoes.br.gov.camara.www;
using System.Data;
using System.Xml;
using SILCD.Models;

namespace SILCD.Controllers {
    public class OrgaosController : BaseController {
        private IOrgaosRepository repositorio;
        private Comissoes servicosComissoes;
        private OrgaoViewModels orgao;

        public OrgaosController(IOrgaosRepository _repositorio) {
            if (repositorio == null) {
                repositorio = _repositorio;
            }
            if (servicosComissoes == null) {
                servicosComissoes = new Comissoes();
            }
        }

        public ActionResult Index() {
            var orgaos = repositorio.Listar((int)TipoDataSource.XML);
            if (orgaos != null) {
                return View(orgaos);
            }
            return View();
        }

        public ActionResult Listar() {

            var orgaos = repositorio.Listar((int)TipoDataSource.XML);

            var filtro = Request["chkFiltroTipo"];
            var filtros = String.IsNullOrEmpty(filtro) ? null : filtro.Split(',');

            //int qtdFiltros = 0;
            //var qryFiltros = String.Empty;
            //foreach (string opcaoFiltro in filtros) {
            //    qtdFiltros++;
            //    qryFiltros += "o => o.Descricao.Contains(\"" + opcaoFiltro + "\")";
            //    qryFiltros += qtdFiltros < filtros.Count() ? " || " : String.Empty;
            //}

            if (!String.IsNullOrEmpty(filtro)) {
                orgaos = orgaos.Where(o => o.Descricao.Contains(filtro)).ToList();
            }

            if (orgaos != null) {
                return PartialView("Listar", orgaos);
            }

            return View();
        }

        //TODO
        [AllowAnonymous]
        public ActionResult Detalhes(int id) {
            if (id > 0) {
                orgao = repositorio.Buscar(id);
                return View(orgao);
            }
            return View();
        }
    }
}

SILCD/Views/Shared/_Grid.cshtml
@using GridMvc.Columns
@model GridMvc.IGrid
@if (Model == null) { return; }
@if (Model.RenderOptions.RenderRowsOnly)
{
    @RenderGridBody();
}
else
{
    <div class="grid-mvc" data-lang="@Model.Language" data-gridname="@Model.RenderOptions.GridName" data-selectable="@Model.RenderOptions.Selectable.ToString().ToLower()" data-multiplefilters ="@Model.RenderOptions.AllowMultipleFilters.ToString().ToLower()">
        <div class="grid-wrap">
            <table class="table table-striped grid-table">
                @* Draw grid header *@
                <thead>
                    @RenderGridHeader()
                </thead>
                <tbody>
                    @RenderGridBody()
                </tbody>
            </table>
            @RenderGridPager()
        </div>
    </div>
}
@helper RenderGridBody()
{
    if (!Model.ItemsToDisplay.Any())
    {
    <tr class="grid-empty-text">
        <td colspan="@Model.Columns.Count()">
            @Model.EmptyGridText
        </td>
    </tr>
    }
    else
    {
        foreach (object item in Model.ItemsToDisplay)
        {
    <tr class="grid-row @Model.GetRowCssClasses(item)">
        @foreach (IGridColumn column in Model.Columns)
        {
            @column.CellRenderer.Render(column, column.GetCell(item))
        }
    </tr>
        }
    }
}
@helper RenderGridHeader()
{
    <tr>
        @foreach (IGridColumn column in Model.Columns)
        {
            @column.HeaderRenderer.Render(column)
        }
    </tr>
}
@helper RenderGridPager()
{
    if (Model.EnablePaging && Model.Pager != null)
    {
    <div class="grid-footer">
        @Html.Partial(Model.Pager.TemplateName, Model.Pager)
    </div>
    }
}

SILCD/Views/Shared/_GridPager.cshtml
@model GridMvc.Pagination.GridPager
@if (Model == null || Model.PageCount <= 1)
{
    return;
}
<div class="grid-pager">
    <ul class="pagination">
        @if (Model.CurrentPage > 1)
        {
            <li>
                <a href="@Model.GetLinkForPage(Model.CurrentPage - 1)">«</a>
            </li>
        }

        @if (Model.StartDisplayedPage > 1)
        {
            <li>
                <a href="@Model.GetLinkForPage(1)">1</a>
            </li>
            if (Model.StartDisplayedPage > 2)
            {
            <li><a href="@Model.GetLinkForPage(Model.StartDisplayedPage - 1)">...</a></li>
            }
        }
        @for (int i = Model.StartDisplayedPage; i <= Model.EndDisplayedPage; i++)
        {
            if (i == Model.CurrentPage)
            {
            <li class="active"><span>@i</span></li>
            }
            else
            {
            <li><a href="@Model.GetLinkForPage(i)">@i</a></li>
            }
        }
        @if (Model.EndDisplayedPage < Model.PageCount)
        {
            if (Model.EndDisplayedPage < Model.PageCount - 1)
            {
            <li><a href="@Model.GetLinkForPage(Model.EndDisplayedPage + 1)">...</a></li>
            }
            <li><a href="@Model.GetLinkForPage(Model.PageCount)">@Model.PageCount</a></li>
        }
        @if (Model.CurrentPage < Model.PageCount)
        {
            <li><a href="@Model.GetLinkForPage(Model.CurrentPage + 1)">»</a></li>
        }
    </ul>
</div>

SILCD/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sistema de Informações Legislativas da Câmara dos Deputados</title>
    @Styles.Render("~/Content/css")
    <link href='http://fonts.googleapis.com/css?family=Carrois+Gothic' rel='stylesheet' type='text/css'>
    @Styles.Render("~/Content/cssgridmvc")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div id="Topo"></div>
    <div class="navbar navbar-default navbar-fixed-top">
        <span class="badge pull-right" style="margin:15px;">beta</span>
        <div class="container">
            <div class="navbar-header">
                @Html.ActionLink("silcd", "Index", "Home", null, new { @class = "navbar-brand title" })
                <small id="smallTitle">Sistema de Informações Legislativas da Câmara dos Deputados</small>
            </div>
            <div class="navbar-collapse collapse pull-right">
                <ul class="nav navbar-nav">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Deputados <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li>
                                <a href="@Url.Action("Index", "Deputados")">
                                    <span class="glyphicon glyphicon-list"></span>
                                    Listar
                                </a>
                            </li>
                            <li>
                                <a href="@Url.Action("DistribuicaoPorUF", "Deputados")">
                                    <span class="glyphicon glyphicon-signal"></span>
                                    Distribuição por UF
                                </a>
                            </li>
                            <li>
                                <a href="@Url.Action("DistribuicaoPorPartido", "Deputados")">
                                    <span class="glyphicon glyphicon-tasks"></span>
                                    Distribuição por Partido
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Órgãos Legislativos <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li>
                                <a href="@Url.Action("Index", "Orgaos")">
                                    <span class="glyphicon glyphicon-list"></span>
                                    Listar
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li><a href="@Url.Action("Index", "CotaParlamentar")">Cotas Parlamentares</a></li>
                </ul>
                <form class="navbar-form navbar-right" role="search" action="@Url.Action("Index", "Deputados")">
                    <div class="form-group">
                        <input id="txtPesquisa" name="txtPesquisa" type="text" class="form-control" placeholder="Pesquisar deputados" title="Pesquise rapidamente por deputados (nome, partido ou uf)">
                    </div>
                    <button type="submit" class="btn btn-info">
                        <span class="glyphicon glyphicon-search"></span>
                    </button>
                </form>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @Scripts.Render("~/bundles/gridmvc")
        @RenderSection("scripts", required: false)

        @RenderBody()
        <hr />
        <footer class="footer text-center">
            <p>&copy; @DateTime.Now.Year - Sistema de Informações Legislativas da Câmara dos Deputados</p>
        </footer>

    </div>

</body>
</html>

SILCD/Views/Shared/_NoRecordsFound.cshtml
<p>Não foram encontrados registros.</p>